spring:
  profiles:
    active: @package.environment@
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  type-aliases-package: com.wwt.managemail.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*Mapper.xml
server:
  port: 8086

yuanbo:
  cors:
    allowedOrigins:
      - http://localhost:8080
      - http://localhost:8081
      - http://localhost:8086
      - http://mf.tianmeihy.com
    allowCredentials: true
    allowedHeaders:
      - "*"
    allowedMethods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
      - HEAD
    maxAge: 3600
    filterPath: "/**"
logging:
  level:
    com.wwt.managemail: debug
