package com.wwt.managemail.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BankProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bank_product
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bank_product
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bank_product
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_product
     *
     * @mbg.generated
     */
    public BankProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_product
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_product
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_product
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_product
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_product
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_product
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_product
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_product
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_product
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_product
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bank_product
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBankIsNull() {
            addCriterion("bank is null");
            return (Criteria) this;
        }

        public Criteria andBankIsNotNull() {
            addCriterion("bank is not null");
            return (Criteria) this;
        }

        public Criteria andBankEqualTo(String value) {
            addCriterion("bank =", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotEqualTo(String value) {
            addCriterion("bank <>", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankGreaterThan(String value) {
            addCriterion("bank >", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankGreaterThanOrEqualTo(String value) {
            addCriterion("bank >=", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLessThan(String value) {
            addCriterion("bank <", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLessThanOrEqualTo(String value) {
            addCriterion("bank <=", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankLike(String value) {
            addCriterion("bank like", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotLike(String value) {
            addCriterion("bank not like", value, "bank");
            return (Criteria) this;
        }

        public Criteria andBankIn(List<String> values) {
            addCriterion("bank in", values, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotIn(List<String> values) {
            addCriterion("bank not in", values, "bank");
            return (Criteria) this;
        }

        public Criteria andBankBetween(String value1, String value2) {
            addCriterion("bank between", value1, value2, "bank");
            return (Criteria) this;
        }

        public Criteria andBankNotBetween(String value1, String value2) {
            addCriterion("bank not between", value1, value2, "bank");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNull() {
            addCriterion("product_type is null");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNotNull() {
            addCriterion("product_type is not null");
            return (Criteria) this;
        }

        public Criteria andProductTypeEqualTo(String value) {
            addCriterion("product_type =", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotEqualTo(String value) {
            addCriterion("product_type <>", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThan(String value) {
            addCriterion("product_type >", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThanOrEqualTo(String value) {
            addCriterion("product_type >=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThan(String value) {
            addCriterion("product_type <", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThanOrEqualTo(String value) {
            addCriterion("product_type <=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLike(String value) {
            addCriterion("product_type like", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotLike(String value) {
            addCriterion("product_type not like", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeIn(List<String> values) {
            addCriterion("product_type in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotIn(List<String> values) {
            addCriterion("product_type not in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeBetween(String value1, String value2) {
            addCriterion("product_type between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotBetween(String value1, String value2) {
            addCriterion("product_type not between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andBankProductIsNull() {
            addCriterion("bank_product is null");
            return (Criteria) this;
        }

        public Criteria andBankProductIsNotNull() {
            addCriterion("bank_product is not null");
            return (Criteria) this;
        }

        public Criteria andBankProductEqualTo(String value) {
            addCriterion("bank_product =", value, "BankProduct");
            return (Criteria) this;
        }

        public Criteria andBankProductNotEqualTo(String value) {
            addCriterion("bank_product <>", value, "BankProduct");
            return (Criteria) this;
        }

        public Criteria andBankProductGreaterThan(String value) {
            addCriterion("bank_product >", value, "BankProduct");
            return (Criteria) this;
        }

        public Criteria andBankProductGreaterThanOrEqualTo(String value) {
            addCriterion("bank_product >=", value, "BankProduct");
            return (Criteria) this;
        }

        public Criteria andBankProductLessThan(String value) {
            addCriterion("bank_product <", value, "BankProduct");
            return (Criteria) this;
        }

        public Criteria andBankProductLessThanOrEqualTo(String value) {
            addCriterion("bank_product <=", value, "BankProduct");
            return (Criteria) this;
        }

        public Criteria andBankProductLike(String value) {
            addCriterion("bank_product like", value, "BankProduct");
            return (Criteria) this;
        }

        public Criteria andBankProductNotLike(String value) {
            addCriterion("bank_product not like", value, "BankProduct");
            return (Criteria) this;
        }

        public Criteria andBankProductIn(List<String> values) {
            addCriterion("bank_product in", values, "BankProduct");
            return (Criteria) this;
        }

        public Criteria andBankProductNotIn(List<String> values) {
            addCriterion("bank_product not in", values, "BankProduct");
            return (Criteria) this;
        }

        public Criteria andBankProductBetween(String value1, String value2) {
            addCriterion("bank_product between", value1, value2, "BankProduct");
            return (Criteria) this;
        }

        public Criteria andBankProductNotBetween(String value1, String value2) {
            addCriterion("bank_product not between", value1, value2, "BankProduct");
            return (Criteria) this;
        }

        public Criteria andExpectedinterestRateIsNull() {
            addCriterion("expectedinterest_rate is null");
            return (Criteria) this;
        }

        public Criteria andExpectedinterestRateIsNotNull() {
            addCriterion("expectedinterest_rate is not null");
            return (Criteria) this;
        }

        public Criteria andExpectedinterestRateEqualTo(Long value) {
            addCriterion("expectedinterest_rate =", value, "expectedinterestRate");
            return (Criteria) this;
        }

        public Criteria andExpectedinterestRateNotEqualTo(Long value) {
            addCriterion("expectedinterest_rate <>", value, "expectedinterestRate");
            return (Criteria) this;
        }

        public Criteria andExpectedinterestRateGreaterThan(Long value) {
            addCriterion("expectedinterest_rate >", value, "expectedinterestRate");
            return (Criteria) this;
        }

        public Criteria andExpectedinterestRateGreaterThanOrEqualTo(Long value) {
            addCriterion("expectedinterest_rate >=", value, "expectedinterestRate");
            return (Criteria) this;
        }

        public Criteria andExpectedinterestRateLessThan(Long value) {
            addCriterion("expectedinterest_rate <", value, "expectedinterestRate");
            return (Criteria) this;
        }

        public Criteria andExpectedinterestRateLessThanOrEqualTo(Long value) {
            addCriterion("expectedinterest_rate <=", value, "expectedinterestRate");
            return (Criteria) this;
        }

        public Criteria andExpectedinterestRateIn(List<Long> values) {
            addCriterion("expectedinterest_rate in", values, "expectedinterestRate");
            return (Criteria) this;
        }

        public Criteria andExpectedinterestRateNotIn(List<Long> values) {
            addCriterion("expectedinterest_rate not in", values, "expectedinterestRate");
            return (Criteria) this;
        }

        public Criteria andExpectedinterestRateBetween(Long value1, Long value2) {
            addCriterion("expectedinterest_rate between", value1, value2, "expectedinterestRate");
            return (Criteria) this;
        }

        public Criteria andExpectedinterestRateNotBetween(Long value1, Long value2) {
            addCriterion("expectedinterest_rate not between", value1, value2, "expectedinterestRate");
            return (Criteria) this;
        }

        public Criteria andInterestPaymentMethodIsNull() {
            addCriterion("interest_payment_method is null");
            return (Criteria) this;
        }

        public Criteria andInterestPaymentMethodIsNotNull() {
            addCriterion("interest_payment_method is not null");
            return (Criteria) this;
        }

        public Criteria andInterestPaymentMethodEqualTo(String value) {
            addCriterion("interest_payment_method =", value, "interestPaymentMethod");
            return (Criteria) this;
        }

        public Criteria andInterestPaymentMethodNotEqualTo(String value) {
            addCriterion("interest_payment_method <>", value, "interestPaymentMethod");
            return (Criteria) this;
        }

        public Criteria andInterestPaymentMethodGreaterThan(String value) {
            addCriterion("interest_payment_method >", value, "interestPaymentMethod");
            return (Criteria) this;
        }

        public Criteria andInterestPaymentMethodGreaterThanOrEqualTo(String value) {
            addCriterion("interest_payment_method >=", value, "interestPaymentMethod");
            return (Criteria) this;
        }

        public Criteria andInterestPaymentMethodLessThan(String value) {
            addCriterion("interest_payment_method <", value, "interestPaymentMethod");
            return (Criteria) this;
        }

        public Criteria andInterestPaymentMethodLessThanOrEqualTo(String value) {
            addCriterion("interest_payment_method <=", value, "interestPaymentMethod");
            return (Criteria) this;
        }

        public Criteria andInterestPaymentMethodLike(String value) {
            addCriterion("interest_payment_method like", value, "interestPaymentMethod");
            return (Criteria) this;
        }

        public Criteria andInterestPaymentMethodNotLike(String value) {
            addCriterion("interest_payment_method not like", value, "interestPaymentMethod");
            return (Criteria) this;
        }

        public Criteria andInterestPaymentMethodIn(List<String> values) {
            addCriterion("interest_payment_method in", values, "interestPaymentMethod");
            return (Criteria) this;
        }

        public Criteria andInterestPaymentMethodNotIn(List<String> values) {
            addCriterion("interest_payment_method not in", values, "interestPaymentMethod");
            return (Criteria) this;
        }

        public Criteria andInterestPaymentMethodBetween(String value1, String value2) {
            addCriterion("interest_payment_method between", value1, value2, "interestPaymentMethod");
            return (Criteria) this;
        }

        public Criteria andInterestPaymentMethodNotBetween(String value1, String value2) {
            addCriterion("interest_payment_method not between", value1, value2, "interestPaymentMethod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodIsNull() {
            addCriterion("deposit_period is null");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodIsNotNull() {
            addCriterion("deposit_period is not null");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodEqualTo(Integer value) {
            addCriterion("deposit_period =", value, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodNotEqualTo(Integer value) {
            addCriterion("deposit_period <>", value, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodGreaterThan(Integer value) {
            addCriterion("deposit_period >", value, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodGreaterThanOrEqualTo(Integer value) {
            addCriterion("deposit_period >=", value, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodLessThan(Integer value) {
            addCriterion("deposit_period <", value, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodLessThanOrEqualTo(Integer value) {
            addCriterion("deposit_period <=", value, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodIn(List<Integer> values) {
            addCriterion("deposit_period in", values, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodNotIn(List<Integer> values) {
            addCriterion("deposit_period not in", values, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodBetween(Integer value1, Integer value2) {
            addCriterion("deposit_period between", value1, value2, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andDepositPeriodNotBetween(Integer value1, Integer value2) {
            addCriterion("deposit_period not between", value1, value2, "depositPeriod");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorTimeIsNull() {
            addCriterion("creator_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatorTimeIsNotNull() {
            addCriterion("creator_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorTimeEqualTo(Date value) {
            addCriterion("creator_time =", value, "creatorTime");
            return (Criteria) this;
        }

        public Criteria andCreatorTimeNotEqualTo(Date value) {
            addCriterion("creator_time <>", value, "creatorTime");
            return (Criteria) this;
        }

        public Criteria andCreatorTimeGreaterThan(Date value) {
            addCriterion("creator_time >", value, "creatorTime");
            return (Criteria) this;
        }

        public Criteria andCreatorTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("creator_time >=", value, "creatorTime");
            return (Criteria) this;
        }

        public Criteria andCreatorTimeLessThan(Date value) {
            addCriterion("creator_time <", value, "creatorTime");
            return (Criteria) this;
        }

        public Criteria andCreatorTimeLessThanOrEqualTo(Date value) {
            addCriterion("creator_time <=", value, "creatorTime");
            return (Criteria) this;
        }

        public Criteria andCreatorTimeIn(List<Date> values) {
            addCriterion("creator_time in", values, "creatorTime");
            return (Criteria) this;
        }

        public Criteria andCreatorTimeNotIn(List<Date> values) {
            addCriterion("creator_time not in", values, "creatorTime");
            return (Criteria) this;
        }

        public Criteria andCreatorTimeBetween(Date value1, Date value2) {
            addCriterion("creator_time between", value1, value2, "creatorTime");
            return (Criteria) this;
        }

        public Criteria andCreatorTimeNotBetween(Date value1, Date value2) {
            addCriterion("creator_time not between", value1, value2, "creatorTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bank_product
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bank_product
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}